repos:
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.168.1
    hooks:
      - id: renovate-config-validator
        language_version: lts # https://github.com/nodejs/node/issues/55410
        args:
          - default.json
          - --strict